title: Reflections
description: Notes and essays
url: "https://4sgupta828.github.io"
baseurl: "/reflections"
theme: minima
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: ""
      type: posts
    values:
      comments: true
utterances:
  repo: "4sgupta828/reflections"
  issue_term: "pathname"
  theme: "github-light"
